import { Storage } from "@google-cloud/storage";

const allowedProjects = () => (process.env.HARMONIA_GCS_PROJECTS ?? process.env.GOOGLE_CLOUD_PROJECT ?? "").split(",").map((value) => value.trim()).filter(Boolean);
export function listAuthorizedProjects(): string[] { return [...new Set(allowedProjects())]; }
export function requireAuthorizedProject(projectId: string): void { if (!allowedProjects().includes(projectId)) throw new Error("GCS project is not authorized"); }
export function normalizePrefix(prefix: string): string { const cleaned = prefix.replace(/^\/+/, "").replace(/\/{2,}/g, "/"); if (cleaned.split("/").includes("..")) throw new Error("GCS prefix traversal is forbidden"); return cleaned && !cleaned.endsWith("/") ? `${cleaned}/` : cleaned; }

export async function listAuthorizedBuckets(projectId: string, storage = new Storage({ projectId })): Promise<string[]> { requireAuthorizedProject(projectId); const [buckets] = await storage.getBuckets({ project: projectId, autoPaginate: false, maxResults: 100 }); return buckets.map((bucket) => bucket.name).sort(); }
export async function listPrefixes(projectId: string, bucket: string, prefix: string, storage = new Storage({ projectId })): Promise<string[]> { requireAuthorizedProject(projectId); const normalized = normalizePrefix(prefix); const [files, , response] = await storage.bucket(bucket).getFiles({ prefix: normalized, delimiter: "/", autoPaginate: false, maxResults: 100 }); void files; return [...new Set(((response as { prefixes?: string[] }).prefixes ?? []).map(normalizePrefix))].sort(); }
export async function listPinnedObjects(projectId: string, bucket: string, prefix: string, pageToken?: string, storage = new Storage({ projectId })) { requireAuthorizedProject(projectId); const [files, nextQuery] = await storage.bucket(bucket).getFiles({ prefix: normalizePrefix(prefix), autoPaginate: false, maxResults: 100, ...(pageToken ? { pageToken } : {}) }); return { objects: files.filter((file) => !file.name.endsWith("/")).map((file) => ({ bucket, name: file.name, generation: file.metadata.generation, size: file.metadata.size, mimeType: file.metadata.contentType, checksum: file.metadata.md5Hash ?? file.metadata.crc32c, updatedAt: file.metadata.updated })), nextPageToken: nextQuery?.pageToken }; }
export async function downloadPinnedObject(projectId: string, bucket: string, name: string, generation: string, storage = new Storage({ projectId })): Promise<Buffer> { requireAuthorizedProject(projectId); const [bytes] = await storage.bucket(bucket).file(name, { generation }).download(); return bytes; }
