"""Direct Gemini media operations plus deterministic content-pack assembly."""

from __future__ import annotations

import json
import os
from typing import Any

from google import genai

from .config import settings
from .mock_ai import mock_ai_enabled, mock_generate_image, mock_transcribe

MODEL = "gemini-3.5-flash"
IMAGE_MODEL = os.environ.get("IMAGE_MODEL_ID", "gemini-3.5-flash-image")


def _client() -> genai.Client:
    key = settings().gemini_api_key
    if not key:
        raise RuntimeError("GEMINI_API_KEY is not configured")
    return genai.Client(api_key=key)


def _parse_json(text: str) -> Any:
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.split("```")[1]
        if cleaned.startswith("json"):
            cleaned = cleaned[4:]
    return json.loads(cleaned)


def model_used() -> str:
    """Label recorded in persisted docs; honest about offline mode."""
    return "mock-local (HARMONIA_MOCK_AI)" if mock_ai_enabled() else MODEL


def transcribe_audio(audio: bytes, mime_type: str) -> dict:
    if mock_ai_enabled():
        print("[MOCK-AI] transcribe_audio: returning deterministic local fixture", flush=True)
        return mock_transcribe(len(audio))
    client = _client()
    res = client.models.generate_content(
        model=MODEL,
        contents=[
            {"role": "user", "parts": [
                {"inlineData": {
                    "mimeType": mime_type,
                    "data": __import__("base64").b64encode(audio).decode(),
                }},
                {"text": (
                    "Transcribe this audio. Return JSON: "
                    "{language, segments:[{id,startSec,endSec,text}]}. "
                    "startSec/endSec are numbers."
                )},
            ]},
        ],
    )
    return _parse_json(res.text)


class ImageGenError(RuntimeError):
    pass


def generate_image(prompt: str) -> tuple[bytes, str]:
    """Generate an image with Gemini and return its bytes and MIME type."""
    if mock_ai_enabled():
        print("[MOCK-AI] generate_image: rendering real local PNG via ffmpeg lavfi", flush=True)
        return mock_generate_image(prompt)
    client = _client()
    try:
        res = client.models.generate_images(model=IMAGE_MODEL, contents=prompt)
        images = getattr(res, "generated_images", None)
        if not images:
            raise ImageGenError(f"{IMAGE_MODEL} returned no images")
        img = images[0].image
        return img.image_bytes, getattr(img, "mime_type", None) or "image/png"
    except ImageGenError:
        raise
    except Exception as exc:  # noqa: BLE001 - normalized for stage failure classification
        raise ImageGenError(f"image generation failed: {exc}") from exc


def build_content_pack(title: str, url: str, moments: list, angles: list, drafts: list) -> str:
    lines = [f"# Harmonia Content Pack — {title}", "", f"Source: {url}", ""]
    lines.append("## Clip moments")
    for moment in moments:
        lines.append(
            f"- **{moment['title']}** ({int(moment['startSec'])}s–{int(moment['endSec'])}s): "
            f"{moment['hook']}"
        )
        lines.append(f'  > "{moment["quote"]}"')
    lines.append("\n## Trend & meme angles")
    for angle in angles:
        lines.append(f"- [{angle['kind'].upper()}] {angle['title']} — {angle['rationale']}")
    lines.append("\n## Ready-to-post drafts")
    for draft in drafts:
        lines.append(f"### {draft['platform'].upper()}")
        lines.append(f"> {draft['text']}")
    lines.append("\n---\nGenerated by Harmonia (Gemini + Google ADK).")
    return "\n".join(lines)
