steps:
  - name: gcr.io/cloud-builders/docker
    args: [pull, '${_CACHE_IMAGE}']
  - name: gcr.io/cloud-builders/docker
    args: [build, '--cache-from', '${_CACHE_IMAGE}', '-t', '${_IMAGE}', '.']
images: ['${_IMAGE}']
