import { randomUUID,createHash } from 'node:crypto';
import { describe,it,expect } from 'vitest';
import { awsRepository,recordKey } from '@/lib/dynamo';
import { runWithTenant } from '@/lib/tenancy';
import { cognitoPrincipal } from '@/lib/authority';
import { sourceRightsAuthorization,persistSourceRightsAuthorization } from '@/lib/sourceRights';
import { reserveJobBudget } from '@/lib/repository';
import { updateKnowledgeIndex,pendingKnowledgeIndexes } from '@/lib/sourceKnowledgeIndex';
import { revokeSourceKnowledge,advanceKnowledgeErasure,listKnowledgeErasures } from '@/lib/sourceKnowledgeErasure';
import { PutObjectCommand,ListObjectVersionsCommand } from '@aws-sdk/client-s3';
import { s3Client } from '@/lib/storage';
const t={workspaceId:`kb-${randomUUID()}`,brandId:'brand',principal:cognitoPrincipal({subjectId:'operator',workspaceRole:'owner',authenticationId:'session'})};
const repo=awsRepository(),root=`workspaces/${t.workspaceId}`,source='source',digest='a'.repeat(64),sourceKey=recordKey(`${root}/brands/brand/sources/${source}`);
const token=createHash('sha256').update(`knowledge-index\0${t.workspaceId}\0brand\0source\0${digest}`).digest('hex');
const input={estimatedCostUsd:'0.001000',pricingVersion:'test-price',estimatedInputUnits:100,jobId:'job',operationId:token,clientToken:token,sourceDigest:digest,objectUri:`s3://${process.env.S3_BUCKET}/knowledge/${t.workspaceId}/brand/source/${digest}.txt`,state:'prepared' as const};
describe.skipIf(!process.env.AWS_LOCAL_ENDPOINT)('native source knowledge authority and erasure',()=>{
 it('binds rights, manifest, digest and provider job before completion; recovers deletion after source removal',async()=>runWithTenant(t,async()=>{
  const rightsAuthorizationId=await persistSourceRightsAuthorization(sourceRightsAuthorization(t,'pasted_text',new Date().toISOString(),'f'.repeat(64)));
  await repo.put(sourceKey,{id:source,workspaceId:t.workspaceId,brandId:t.brandId,state:'ready',provider:'pasted_text',rightsAuthorizationId,contentDigest:digest});
  await repo.put(recordKey(`${root}/jobs/job`),{workspaceId:t.workspaceId,brandId:t.brandId,config:{sourceManifestId:'manifest'}});
  await repo.put(recordKey(root),{budget:{estimatedUsd:'0',observedUsd:'0',reservedUsd:'0',limitUsd:'10',approvalThresholdUsd:'10'}});
  await reserveJobBudget({jobId:'job',operationId:token,stage:'extract_sources',role:'knowledge_index',model:'amazon.titan-embed-text-v2:0',estimatedCostUsd:'0.001000',pricingVersion:'test-price'});
  const usageRecord={id:`knowledge-index-${token}`,jobId:'job',operationId:token,stage:'extract_sources',role:'knowledge_index',model:'amazon.titan-embed-text-v2:0',inputUnits:100,outputUnits:0,unitType:'tokens' as const,estimatedCostUsd:'0.001000',pricingVersion:'test-price',measurementBasis:'utf8_byte_token_upper_bound' as const,observedCostUnavailable:true,traceId:token.slice(0,32),createdAt:new Date().toISOString()};
  await repo.put(recordKey(`${root}/jobs/job/source_manifests/manifest`),{directSourceIds:[source],excludedSourceIds:[]});
  await expect(updateKnowledgeIndex(source,{...input,operationId:'b'.repeat(64)})).rejects.toThrow('identity');
  await expect(updateKnowledgeIndex(source,{...input,state:'complete',ingestionJobId:'job-id'})).rejects.toThrow('prepared');
  const rightsKey=recordKey(`${root}/brands/brand/source_rights/${rightsAuthorizationId}`);
  await repo.patch(rightsKey,{revokedAt:new Date().toISOString()});
  await expect(updateKnowledgeIndex(source,input)).rejects.toThrow('revoked');
  await repo.patch(rightsKey,{revokedAt:null});
  await updateKnowledgeIndex(source,input);
  expect(await pendingKnowledgeIndexes()).toHaveLength(1);
  await expect(updateKnowledgeIndex(source,{...input,state:'complete',ingestionJobId:'job-id'})).rejects.toThrow('submitted');
  await updateKnowledgeIndex(source,{...input,state:'submitted',ingestionJobId:'job-id'});
  await expect(updateKnowledgeIndex(source,{...input,state:'complete',ingestionJobId:'wrong'})).rejects.toThrow('submitted');
  await updateKnowledgeIndex(source,{...input,state:'complete',ingestionJobId:'job-id',usageRecord});
  expect((await repo.read(recordKey(`${root}/jobs/job/cost_reservations/${token}`))).value?.state).toBe('finalized');
  await repo.put(recordKey(`${root}/jobs/second`),{workspaceId:t.workspaceId,brandId:t.brandId,config:{sourceManifestId:'manifest'}});
  await repo.put(recordKey(`${root}/jobs/second/source_manifests/manifest`),{directSourceIds:[source],excludedSourceIds:[]});
  expect((await updateKnowledgeIndex(source,{...input,jobId:'second'})).jobId).toBe('job');
  expect(await pendingKnowledgeIndexes()).toHaveLength(0);
  const budgetBefore=(await repo.read(recordKey(root))).value?.budget;
  await updateKnowledgeIndex(source,{...input,state:'complete',ingestionJobId:'job-id',usageRecord});
  expect((await repo.read(recordKey(root))).value?.budget).toEqual(budgetBefore);
  const secondToken=createHash('sha256').update(`knowledge-index\0${t.workspaceId}\0brand\0source2\0${digest}`).digest('hex');
  await repo.put(recordKey(`${root}/brands/brand/sources/source2`),{id:'source2',workspaceId:t.workspaceId,brandId:t.brandId,state:'ready',provider:'pasted_text',rightsAuthorizationId,contentDigest:digest});
  await repo.put(recordKey(`${root}/jobs/job/source_manifests/manifest`),{directSourceIds:[source,'source2'],excludedSourceIds:[]});
  await reserveJobBudget({jobId:'job',operationId:secondToken,stage:'extract_sources',role:'knowledge_index',model:'amazon.titan-embed-text-v2:0',estimatedCostUsd:'0.001000',pricingVersion:'test-price'});
  const secondInput={...input,operationId:secondToken,clientToken:secondToken,objectUri:input.objectUri.replace('/source/','/source2/')};
  await updateKnowledgeIndex('source2',secondInput);
  await repo.patch(recordKey(`${root}/brands/brand/sources/source2`),{state:'excluded'});
  await updateKnowledgeIndex('source2',{...secondInput,state:'failed',budgetOutcome:'not_invoked',error:'source revoked before dispatch'});
  expect((await repo.read(recordKey(`${root}/jobs/job/cost_reservations/${secondToken}`))).value?.state).toBe('released');

  const bucket=process.env.S3_BUCKET!,key=`knowledge/${t.workspaceId}/brand/source/${digest}.txt`,sibling=`knowledge/${t.workspaceId}/brand/other/${digest}.txt`;
  await s3Client().send(new PutObjectCommand({Bucket:bucket,Key:key,Body:'first'}));
  await s3Client().send(new PutObjectCommand({Bucket:bucket,Key:key,Body:'second'}));
  await s3Client().send(new PutObjectCommand({Bucket:bucket,Key:sibling,Body:'keep'}));
  const id=(await revokeSourceKnowledge(source))!;
  expect((await repo.read(sourceKey)).value?.state).toBe('excluded');
  await expect(updateKnowledgeIndex(source,input)).rejects.toThrow('authority changed');
  await repo.removeTree(sourceKey);
  await expect(advanceKnowledgeErasure(id,'s3_erased')).rejects.toThrow('grace');
  await repo.patch(recordKey('knowledge-erasure/'+id),{notBefore:new Date(0).toISOString()});
  expect((await listKnowledgeErasures()).some(r=>r?.id===id)).toBe(true);
  await advanceKnowledgeErasure(id,'s3_erased');
  expect((await s3Client().send(new ListObjectVersionsCommand({Bucket:bucket,Prefix:key}))).Versions??[]).toHaveLength(0);
  expect((await s3Client().send(new ListObjectVersionsCommand({Bucket:bucket,Prefix:sibling}))).Versions).toHaveLength(1);
  await expect(advanceKnowledgeErasure(id,'complete','sync')).rejects.toThrow('reconciliation');
  await advanceKnowledgeErasure(id,'sync_submitted','sync');
  await advanceKnowledgeErasure(id,'complete','sync');
  expect((await listKnowledgeErasures()).some(r=>r?.id===id)).toBe(false);
  await s3Client().send(new PutObjectCommand({Bucket:bucket,Key:key,Body:'late in-flight write'}));
  await repo.patch(recordKey('knowledge-erasure/'+id),{nextAuditAt:new Date(0).toISOString()});
  await listKnowledgeErasures();
  const reopened=(await repo.read(recordKey('knowledge-erasure/'+id))).value!;
  expect(reopened.state).toBe('pending');expect(reopened.clientToken).not.toBe(id);
  await repo.patch(recordKey('knowledge-erasure/'+id),{notBefore:new Date(0).toISOString()});
  await advanceKnowledgeErasure(id,'s3_erased');
  expect((await s3Client().send(new ListObjectVersionsCommand({Bucket:bucket,Prefix:key}))).Versions??[]).toHaveLength(0);
 }));
});
