from harmonia_agent.content import build_content_pack


def test_content_pack_does_not_claim_unobserved_model_or_framework_provenance():
    pack = build_content_pack(
        "Launch interview",
        "https://www.youtube.com/watch?v=authorized-source",
        [{
            "title": "Approval boundary", "startSec": 12, "endSec": 34,
            "hook": "Authority remains explicit", "quote": "The operator authorizes.",
        }],
        [{"kind": "insight", "title": "Bounded autonomy", "rationale": "Safety is part of the product."}],
        [{"platform": "x", "text": "Autonomy needs explicit authority."}],
    )

    assert "Assembled by Harmonia from persisted pipeline artifacts." in pack
    assert "Generated by Harmonia (Gemini + Google ADK)." not in pack
