import { advance } from "@/lib/advance";
import { db, getJob, setStage } from "@/lib/firestore";
import { getArtifact } from "@/lib/storage";
import { isInternalAuthorized, unauthorized, withInternalTenant } from "@/lib/internalAuth";
import { currentTenant } from "@/lib/tenancy";
import { z } from "zod";
export async function GET(request: Request) { if (!isInternalAuthorized(request)) return unauthorized(); return withInternalTenant(request, async () => { const jobId = new URL(request.url).searchParams.get("jobId"); if (!jobId) return Response.json({ error: "jobId required" }, { status: 400 }); const tenant = currentTenant(); const job = await getJob(jobId); const manifest = await db().doc(`workspaces/${tenant.workspaceId}/jobs/${jobId}/source_manifests/${job.config.sourceManifestId}`).get(); if (!manifest.exists) return Response.json({ error: "source manifest not found" }, { status: 404 }); const data = manifest.data()!; let ids = [...((data.directSourceIds as string[] | undefined) ?? [])]; if (data.librarySnapshotId) { const libraries = await db().collection(`workspaces/${tenant.workspaceId}/brands/${tenant.brandId}/brand_libraries`).get(); for (const library of libraries.docs) { const snapshot = await library.ref.collection("snapshots").doc(data.librarySnapshotId).get(); if (snapshot.exists) { ids.push(...((snapshot.get("fileVersions") as Array<{ sourceId: string }> | undefined) ?? []).filter((item) => item).map((item) => item.sourceId)); break; } } } const excluded = new Set((data.excludedSourceIds as string[] | undefined) ?? []); ids = [...new Set(ids)].filter((id) => !excluded.has(id)); const sources = (await Promise.all(ids.map(async (id) => { const snapshot = await db().doc(`workspaces/${tenant.workspaceId}/brands/${tenant.brandId}/sources/${id}`).get(); return snapshot.exists ? snapshot.data() : null; }))).filter(Boolean); const normalizedSources = (await Promise.all(sources.map(async (source) => { const artifactId = (source as { normalizedArtifactId?: string }).normalizedArtifactId; if (!artifactId) return null; const body = await getArtifact(artifactId); return body ? JSON.parse(body.toString("utf8")) : null; }))).filter(Boolean); return Response.json({ manifest: data, sources, normalizedSources }); }); }
const completionSchema = z.object({ jobId: z.string().min(1), stage: z.enum(["collect_sources", "extract_sources"]), outcome: z.enum(["all_ready", "partial_failure"]) }).strict();
export async function POST(request: Request) { if (!isInternalAuthorized(request)) return unauthorized(); return withInternalTenant(request, async () => { const parsed = completionSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return Response.json({ error: "invalid source-stage completion" }, { status: 400 }); if (parsed.data.outcome === "partial_failure") { await setStage(parsed.data.jobId, "awaiting_source_resolution", "waiting_for_approval"); return Response.json({ ok: true, nextStage: "awaiting_source_resolution" }); } if (parsed.data.stage === "collect_sources") await advance(parsed.data.jobId, "collect_sources", "sources validated and queued"); else await advance(parsed.data.jobId, "extract_sources", "all selected sources extracted"); return Response.json({ ok: true }); }); }
