import { advance } from "@/lib/advance";
import { isInternalAuthorized,unauthorized,withInternalTenant } from "@/lib/internalAuth";
import { getJob,setStage } from "@/lib/repository";
import { getArtifact } from "@/lib/storage";
import { currentTenant } from "@/lib/tenancy";
import { z } from "zod";
import { awsRepository,field,partition,recordKey } from "../../../../lib/dynamo";
export async function GET(request: Request) { if (!isInternalAuthorized(request)) return unauthorized(); return withInternalTenant(request, async () => { const jobId = new URL(request.url).searchParams.get("jobId"); if (!jobId) return Response.json({ error: "jobId required" }, { status: 400 }); const tenant = currentTenant(); const job = await getJob(jobId); const manifest = await awsRepository().read(recordKey(`workspaces/${tenant.workspaceId}/jobs/${jobId}/source_manifests/${job.config.sourceManifestId}`)); if (!manifest.present) return Response.json({ error: "source manifest not found" }, { status: 404 }); const data = manifest.value!; let ids = [...((data.directSourceIds as string[] | undefined) ?? [])]; if (data.librarySnapshotId) { const libraries = await awsRepository().query(partition(`workspaces/${tenant.workspaceId}/brands/${tenant.brandId}/brand_libraries`)); for (const library of libraries.rows) { const snapshot = await awsRepository().read(recordKey(partition(library.key.path + "/" + "snapshots").partition + "/" + data.librarySnapshotId)); if (snapshot.present) { ids.push(...((field(snapshot.value, "fileVersions") as Array<{ sourceId: string }> | undefined) ?? []).filter((item) => item).map((item) => item.sourceId)); break; } } } const excluded = new Set((data.excludedSourceIds as string[] | undefined) ?? []); ids = [...new Set(ids)].filter((id) => !excluded.has(id)); const sources = (await Promise.all(ids.map(async (id) => { const snapshot = await awsRepository().read(recordKey(`workspaces/${tenant.workspaceId}/brands/${tenant.brandId}/sources/${id}`)); return snapshot.present ? snapshot.value : null; }))).filter(Boolean); const normalizedSources = (await Promise.all(sources.map(async (source) => { const artifactId = (source as { normalizedArtifactId?: string }).normalizedArtifactId; if (!artifactId) return null; const body = await getArtifact(artifactId); return body ? JSON.parse(body.toString("utf8")) : null; }))).filter(Boolean); return Response.json({ manifest: data, sources, normalizedSources }); }); }
const completionSchema = z.object({ jobId: z.string().min(1), stage: z.enum(["collect_sources", "extract_sources"]), outcome: z.enum(["all_ready", "partial_failure"]) }).strict();
export async function POST(request: Request) { if (!isInternalAuthorized(request)) return unauthorized(); return withInternalTenant(request, async () => { const parsed = completionSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return Response.json({ error: "invalid source-stage completion" }, { status: 400 }); if (parsed.data.outcome === "partial_failure") { await setStage(parsed.data.jobId, "awaiting_source_resolution", "waiting_for_approval"); return Response.json({ ok: true, nextStage: "awaiting_source_resolution" }); } if (parsed.data.stage === "collect_sources") { await advance(parsed.data.jobId, "collect_sources", "sources validated and queued"); return Response.json({ ok: true, nextStage: "extract_sources" }); } await advance(parsed.data.jobId, "extract_sources", "all selected sources extracted"); return Response.json({ ok: true, nextStage: "understand" }); }); }
