"use client";

import { useCallback, useEffect, useState } from "react";
import { apiFetch } from "@/lib/clientApi";
import { Button } from "@/components/dashboard/Button";
import { SectionHeader } from "@/components/dashboard/DashboardPage";
import { StatusBadge } from "@/components/dashboard/StatusBadge";
import { Surface } from "@/components/dashboard/Surface";

interface Library { id: string; name: string; cadence: string; lastSyncStatus: string; currentHealthySnapshotId?: string; selector: { provider: "google_drive"; folderId: string } | { provider: "gcs"; projectId: string; bucket: string; prefix: string } }
interface Option { id: string; name: string }

export function BrandLibrariesSettings() {
  const [libraries, setLibraries] = useState<Library[]>([]); const [provider, setProvider] = useState<"google_drive" | "gcs">("google_drive");
  const [folders, setFolders] = useState<Option[]>([]); const [folderId, setFolderId] = useState(""); const [projects, setProjects] = useState<string[]>([]); const [projectId, setProjectId] = useState(""); const [buckets, setBuckets] = useState<string[]>([]); const [bucket, setBucket] = useState(""); const [prefixes, setPrefixes] = useState<string[]>([]); const [prefix, setPrefix] = useState(""); const [cadence, setCadence] = useState("six_hours"); const [status, setStatus] = useState("");
  const load = useCallback(() => apiFetch("/api/settings/libraries").then((response) => response.json()).then((data) => setLibraries(data.libraries ?? [])).catch(() => setStatus("Could not load brand libraries.")), []);
  useEffect(() => { load(); apiFetch("/api/settings/libraries/gcs/projects").then((response) => response.json()).then((data) => setProjects(data.projects ?? [])).catch(() => undefined); }, [load]);
  useEffect(() => { if (provider === "google_drive") apiFetch("/api/settings/libraries/google-drive/folders").then((response) => response.ok ? response.json() : Promise.reject()).then((data) => setFolders(data.folders ?? [])).catch(() => setFolders([])); }, [provider]);
  useEffect(() => { if (projectId) apiFetch(`/api/settings/libraries/gcs/buckets?projectId=${encodeURIComponent(projectId)}`).then((r) => r.json()).then((data) => setBuckets(data.buckets ?? [])).catch(() => setBuckets([])); }, [projectId]);
  useEffect(() => { if (projectId && bucket) apiFetch(`/api/settings/libraries/gcs/prefixes?projectId=${encodeURIComponent(projectId)}&bucket=${encodeURIComponent(bucket)}&prefix=${encodeURIComponent(prefix)}`).then((r) => r.json()).then((data) => setPrefixes(data.prefixes ?? [])).catch(() => setPrefixes([])); }, [projectId, bucket, prefix]);
  async function create() { const selector = provider === "google_drive" ? { provider, driveId: "my-drive", folderId } : { provider, projectId, bucket, prefix }; const response = await apiFetch("/api/settings/libraries", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: provider === "google_drive" ? folders.find((item) => item.id === folderId)?.name ?? "Drive library" : `${bucket}/${prefix}`, selector, cadence }) }); const body = await response.json(); setStatus(response.ok ? "Brand library connected." : body.error ?? "Connection failed."); if (response.ok) load(); }
  async function syncNow(id: string) { const response = await apiFetch(`/api/settings/libraries/${encodeURIComponent(id)}/sync`, { method: "POST" }); const body = await response.json(); setStatus(response.ok ? `Sync queued: ${body.operationId}` : body.error ?? "Sync could not start."); if (response.ok) load(); }
  const valid = provider === "google_drive" ? Boolean(folderId) : Boolean(projectId && bucket);
  return <Surface as="section" className="settings-section"><SectionHeader title="Brand libraries" description="Select authorized Drive folders or GCS prefixes. Harmonia snapshots them on a schedule; jobs pin one immutable healthy snapshot." metadata={<StatusBadge tone={libraries.length ? "success" : "neutral"}>{libraries.length} connected</StatusBadge>} />
    <div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="text-xs">Provider<select aria-label="Library provider" value={provider} onChange={(event) => setProvider(event.target.value as typeof provider)} className="mt-1 w-full rounded border p-2"><option value="google_drive">Google Drive</option><option value="gcs">Google Cloud Storage</option></select></label><label className="text-xs">Sync schedule<select aria-label="Sync schedule" value={cadence} onChange={(event) => setCadence(event.target.value)} className="mt-1 w-full rounded border p-2"><option value="hourly">Hourly</option><option value="six_hours">Every 6 hours</option><option value="daily">Daily</option><option value="paused">Paused</option></select></label></div>
    {provider === "google_drive" ? <div className="mt-3"><a href="/api/oauth/google-drive/authorize" className="text-xs underline">Connect or reconnect Google Drive</a><select aria-label="Google Drive folder" value={folderId} onChange={(event) => setFolderId(event.target.value)} className="mt-2 w-full rounded border p-2"><option value="">Select a Drive folder…</option>{folders.map((folder) => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select></div> : <div className="mt-3 grid gap-2 sm:grid-cols-3"><select aria-label="GCS project" value={projectId} onChange={(event) => { setProjectId(event.target.value); setBucket(""); setPrefix(""); }} className="rounded border p-2"><option value="">Select project…</option>{projects.map((project) => <option key={project}>{project}</option>)}</select><select aria-label="GCS bucket" value={bucket} onChange={(event) => { setBucket(event.target.value); setPrefix(""); }} className="rounded border p-2"><option value="">Select bucket…</option>{buckets.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="GCS prefix" value={prefix} onChange={(event) => setPrefix(event.target.value)} className="rounded border p-2"><option value="">Bucket root</option>{prefixes.map((item) => <option key={item}>{item}</option>)}</select></div>}
    <div className="mt-3 flex items-center gap-2"><Button variant="primary" disabled={!valid} onClick={create}>Add brand library</Button>{status ? <span className="text-xs">{status}</span> : null}</div>
    <ul className="mt-4 space-y-2">{libraries.map((library) => <li key={library.id} className="rounded border p-3 text-xs"><b>{library.name}</b><span className="ml-2">{library.selector.provider} · {library.cadence} · {library.lastSyncStatus}</span>{library.currentHealthySnapshotId ? <code className="mt-1 block">snapshot {library.currentHealthySnapshotId}</code> : <span className="mt-1 block text-amber-700">No healthy snapshot yet</span>}<Button className="mt-2" disabled={library.lastSyncStatus === "running" || library.cadence === "paused"} onClick={() => syncNow(library.id)}>Sync now</Button></li>)}</ul>
  </Surface>;
}
