"use client";
import { useState } from "react";
import { apiFetch } from "@/lib/clientApi";
import type { SourceRecord } from "@/lib/types";

export function SourceResolutionPanel({ jobId, sources }: { jobId: string; sources: SourceRecord[] }) {
  const failed = sources.filter((source) => source.state === "failed"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [replacement, setReplacement] = useState("");
  async function resolve(body: Record<string, unknown>) { setBusy(true); setError(""); try { const response = await apiFetch(`/api/jobs/${jobId}/sources/resolve`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "resolution failed"); if (result.reconnectUrl) window.location.assign(result.reconnectUrl); else window.location.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); setBusy(false); } }
  return <section className="border-2 border-[#ff5c35] bg-[#fff2ea] p-4"><p className="text-[9px] font-black uppercase tracking-[0.18em] text-[#ff5c35]">Operator resolution required</p><h3 className="font-serif text-xl">{failed.length} source{failed.length === 1 ? "" : "s"} need attention</h3>{failed.map((source) => <article key={source.id} className="mt-3 border-t border-black/15 pt-3"><strong className="text-sm">{source.title}</strong><p className="text-xs text-black/60">{source.failure?.publicMessage ?? "Extraction failed"}</p><div className="mt-2 flex flex-wrap gap-2"><button disabled={busy} onClick={() => void resolve({ action: "retry", sourceId: source.id })} className="rounded-full bg-black px-3 py-1 text-[9px] font-bold text-white">Retry</button><button disabled={busy} onClick={() => void resolve({ action: "remove", sourceId: source.id, reason: "Operator removed failed source" })} className="rounded-full border border-black px-3 py-1 text-[9px] font-bold">Remove</button>{["google_drive", "gcs"].includes(source.provider) ? <button disabled={busy} onClick={() => void resolve({ action: "reconnect", sourceId: source.id })} className="rounded-full border border-black px-3 py-1 text-[9px] font-bold">Reconnect</button> : null}</div><div className="mt-2 flex gap-2"><input value={replacement} onChange={(event) => setReplacement(event.target.value)} placeholder="Replacement public URL or pasted text" className="min-w-0 flex-1 border border-black/20 bg-white px-2 py-1 text-xs"/><button disabled={busy || !replacement.trim()} onClick={() => void resolve({ action: "replace", sourceId: source.id, reason: "Operator replaced failed source", replacement: /^https?:\/\//i.test(replacement) ? { kind: "web", url: replacement } : { kind: "pasted_text", title: `Replacement for ${source.title}`, text: replacement } })} className="rounded-full border border-black px-3 py-1 text-[9px] font-bold">Replace</button></div></article>)}<button disabled={busy} onClick={() => void resolve({ action: "continue" })} className="mt-4 rounded-full bg-[#3157ff] px-4 py-2 text-[10px] font-black uppercase text-white">Continue without failed sources</button>{error ? <p className="mt-2 text-xs text-red-700">{error}</p> : null}</section>;
}
