import type { JobFull, Receipt } from "@/components/jobTypes";

function timestamp(seconds: number) {
  return `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, "0")}`;
}

export function SourcesWorkspace({ job, receipts }: { job: JobFull; receipts: Receipt[] }) {
  return (
    <div className="grid gap-5 xl:grid-cols-[1.35fr_1fr]">
      <section className="border border-black/15 bg-[#fffdf7] p-5"><div className="mb-4 flex items-end justify-between"><div><p className="text-[9px] font-black uppercase tracking-[0.18em] text-[#3157ff]">Ground truth</p><h3 className="font-serif text-2xl">Transcript</h3></div><span className="font-mono text-[10px] text-black/40">{job.transcriptSegments.length} segments</span></div><ol className="max-h-[56vh] space-y-3 overflow-y-auto pr-2">{job.transcriptSegments.map((segment) => <li key={segment.id} data-canvas-artifact={`source:${segment.id}`} className="grid grid-cols-[3.5rem_1fr] gap-3 border-t border-black/10 pt-3"><span className="font-mono text-xs text-[#ff5c35]">{timestamp(segment.startSec)}</span><p className="text-sm leading-6 text-black/70">{segment.text}</p></li>)}</ol>{!job.transcriptSegments.length ? <p className="py-8 text-sm text-black/40">No transcript has been persisted for this job.</p> : null}</section>
      <div className="space-y-5">
        {job.contentStrategy ? <section className="border border-black/15 bg-[#f0edff] p-5" data-canvas-artifact="strategy:current"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[0.18em] text-[#5165ff]">Ryan strategy · v{job.contentStrategy.version}</p><h3 className="mt-1 font-serif text-xl">{job.contentStrategy.thesis}</h3></div><span className="rounded-full border border-black/15 px-2 py-1 font-mono text-[8px]">{job.strategyApprovalState ?? "pending"}</span></div><p className="mt-3 text-xs leading-5 text-black/60">{job.contentStrategy.differentiatedNarrative}</p><dl className="mt-4 grid grid-cols-3 gap-2 text-xs"><div><dt className="text-black/40">Horizon</dt><dd>{job.contentStrategy.horizonWeeks} weeks</dd></div><div><dt className="text-black/40">Confidence</dt><dd>{job.contentStrategy.confidence}</dd></div><div><dt className="text-black/40">Briefs</dt><dd>{job.contentStrategy.briefs.length}</dd></div></dl><div className="mt-4 flex flex-wrap gap-1">{job.contentStrategy.pillars.map((pillar) => <span key={pillar.name} className="rounded-full bg-white px-2 py-1 text-[9px]">{pillar.name}</span>)}</div><details className="mt-4"><summary className="cursor-pointer text-[10px] font-bold uppercase">Briefs and provenance</summary><ol className="mt-2 space-y-2">{job.contentStrategy.briefs.map((brief) => <li key={brief.id} className="border-t border-black/10 pt-2 text-xs"><b>{brief.title}</b><p className="mt-1 text-black/55">{brief.keyMessage}</p><code className="mt-1 block text-[9px] text-black/40">{brief.evidenceRefs.join(" · ")}</code></li>)}</ol>{job.contentStrategy.assumptions.length ? <ul className="mt-3 text-[10px] text-black/50">{job.contentStrategy.assumptions.map((item) => <li key={item.text}>Assumption ({item.confidence}): {item.text}</li>)}</ul> : null}</details></section> : null}
        <section className="border border-black/15 bg-[#d9ff43]/30 p-5"><h3 className="font-serif text-xl">Detected moments</h3><div className="mt-3 space-y-3">{job.moments.map((moment) => <article key={moment.id} className="border-t border-black/15 pt-3"><div className="flex justify-between gap-3"><strong className="text-sm">{moment.title}</strong><span className="shrink-0 font-mono text-[10px]">{timestamp(moment.startSec)}–{timestamp(moment.endSec)}</span></div><p className="mt-1 text-xs leading-5 text-black/60">{moment.hook}</p>{moment.cropSuitability ? <span className="mt-2 inline-block bg-white/70 px-2 py-1 text-[9px] font-bold uppercase">crop {moment.cropSuitability}</span> : null}</article>)}</div></section>
        <section className="border border-black/15 bg-[#fffdf7] p-5"><h3 className="font-serif text-xl">Narrative angles</h3><div className="mt-3 space-y-3">{job.angles.map((angle) => <article key={angle.id}><span className="text-[9px] font-black uppercase tracking-wider text-[#8d5cff]">{angle.kind}</span><strong className="block text-sm">{angle.title}</strong><p className="mt-1 text-xs leading-5 text-black/55">{angle.rationale}</p></article>)}</div></section>
        <section className="border border-black/15 bg-[#17151e] p-5 text-white"><div className="flex justify-between"><h3 className="font-serif text-xl">Receipts & verification</h3><span className="font-mono text-xs text-white/45">{receipts.length}</span></div><ul className="mt-3 space-y-2">{receipts.map((receipt) => <li key={receipt.id} className="border-t border-white/15 pt-2 text-xs"><div className="flex justify-between gap-2"><span>{receipt.actionType}</span><span className={receipt.outcome === "applied" || receipt.outcome === "already_applied" ? "text-[#d9ff43]" : "text-[#ff896d]"}>{receipt.outcome}</span></div>{receipt.artifact?.url ? <a href={receipt.artifact.url} target="_blank" rel="noreferrer" className="mt-1 block truncate font-mono text-[10px] text-white/45 underline">{receipt.artifact.url}</a> : null}</li>)}</ul>{!receipts.length ? <p className="mt-3 text-xs text-white/45">No execution receipts exist yet.</p> : null}{(job.verifications ?? []).map((verification) => <div key={verification.rubricItemId} className="mt-3 border-t border-white/15 pt-3 text-xs"><span className={verification.verified ? "text-[#d9ff43]" : "text-[#ff896d]"}>{verification.verified ? "Verified" : "Unverified"}</span> · {verification.method}{verification.evidence.url ? <a href={verification.evidence.url} target="_blank" rel="noreferrer" className="ml-2 underline">evidence</a> : null}</div>)}</section>
      </div>
    </div>
  );
}
