"use client";
import { useState } from "react";
import { apiFetch } from "@/lib/clientApi";
import type { JobFull } from "@/components/jobTypes";

export function SteeringControls({ job }: { job: JobFull }) { const [instruction, setInstruction] = useState(""); const [impact, setImpact] = useState<{ nudge: { id: string }; impact: { digest: string; invalidatedStages: string[]; revokesApprovals: boolean; preservesExecutedReceipts: boolean } } | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const epoch = job.controlEpoch ?? 0;
  async function call(path: string, body: unknown) { setBusy(true); setError(""); try { const response = await apiFetch(path, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "steering failed"); return result; } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); return null; } finally { setBusy(false); } }
  async function propose() { const result = await call(`/api/jobs/${job.id}/steering/nudges`, { scope: "remaining_job", instruction }); if (result) setImpact(result); }
  async function apply() { if (!impact) return; const result = await call(`/api/jobs/${job.id}/steering/nudges/${impact.nudge.id}/apply`, { impactDigest: impact.impact.digest }); if (result) window.location.reload(); }
  return <section className="mt-3 rounded-lg border border-zinc-200 bg-zinc-50 p-3 dark:border-zinc-800 dark:bg-zinc-950"><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-wider">Job control · {job.controlState ?? "running"} · epoch {epoch}</span>{job.controlState === "paused" ? <button disabled={busy} onClick={async () => { if (await call(`/api/jobs/${job.id}/steering/resume`, { expectedControlEpoch: epoch })) window.location.reload(); }} className="rounded-full bg-emerald-700 px-3 py-1 text-[10px] text-white">Resume</button> : <button disabled={busy || job.controlState === "cancelled"} onClick={async () => { if (await call(`/api/jobs/${job.id}/steering/pause`, { expectedControlEpoch: epoch })) window.location.reload(); }} className="rounded-full border px-3 py-1 text-[10px]">Pause</button>}</div><div className="mt-2 flex gap-2"><input value={instruction} onChange={(event) => { setInstruction(event.target.value); setImpact(null); }} placeholder="Steer the remaining job…" className="min-w-0 flex-1 rounded border bg-white px-2 py-1 text-xs dark:bg-black"/><button disabled={busy || instruction.trim().length < 3} onClick={() => void propose()} className="rounded-full border px-3 py-1 text-[10px]">Review impact</button></div>{impact ? <div className="mt-2 rounded border border-amber-300 bg-amber-50 p-2 text-[10px] text-black"><p>Invalidates: {impact.impact.invalidatedStages.join(" → ") || "no downstream stages"}</p><p>{impact.impact.revokesApprovals ? "Existing downstream approval is revoked. " : ""}Executed receipts are preserved.</p><button disabled={busy} onClick={() => void apply()} className="mt-2 rounded-full bg-black px-3 py-1 text-white">Apply exact impact</button></div> : null}{error ? <p className="mt-2 text-xs text-red-600">{error}</p> : null}</section>; }
